### PR TITLE
Fix format error

### PR DESCRIPTION
**Pull request by delirious-lettuce**
```python
>>> TypeError("Must be of type {p}".format(type(p='test')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type() takes 1 or 3 arguments
>>> TypeError("Must be of type {p}".format(p=type('test')))
TypeError("Must be of type <type 'str'>",)

```

### CODE REVIEW

**Review by mertzjames — APPROVED** [review]
nice catch!

**Comment by mertzjames** [comment]
This shouldn't be merged directly into production though.  let's use dev instead.

**Comment by mertzjames** [comment]
interesting that the test `test_pktfield_raises_typeerror_when_not_pktclas` didn't catch this properly.

**Comment by delirious-lettuce** [comment]
Sorry about that, my mistake! I think that other typo pr was to prod too
now that I think about it.

Should I close these and resubmit them to dev?

**Comment by mertzjames** [comment]
nah.  Github allows me to change the branch (which I already did).  It's all good.  Thanks for the contributions!

**Comment by delirious-lettuce** [comment]
Oh ok, cool. I haven’t ever had a repo that other people sent a pr too so
that is news to me!

Although I’m not sure I can really help with your project, I will make sure
to send any potential future prs to dev.

Thanks for your time!

**Comment by delirious-lettuce** [comment]
@KronoSKoderS ,

> interesting that the test test_pktfield_raises_typeerror_when_not_pktclas didn't catch this properly.

Ya, I guess because trying to create the `TypeError` was raising a `TypeError` and the test was looking for a `TypeError` to be raised. Maybe also testing the actual error message inside the `TypeError` as well would be better?

```python
import unittest


class TestCase(unittest.TestCase):
    def test_pktfield_raises_typeerror_when_not_pktclas(self):
        with self.assertRaises(TypeError) as error:
            raise TypeError('custom message')

        self.assertEqual(str(error.exception), 'custom message')


if __name__ == '__main__':
    unittest.main()
```

Just a quick example but using `assertRegex` (Python 3) and `assertRegexpMatches` (Python 2) would probably be better since the type in the actual message could change.

**Comment by mertzjames** [comment]
Huh, I'll have to look into this a little more.

**Comment by delirious-lettuce** [comment]
@KronoSKoderS ,

Ok, cool

**Pull request merged**
